version: 1.0
phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # Install dependencies
  build:
    commands:
      - echo Building Flask app...
      - export FLASK_APP=app.py
      - export FLASK_ENV=production
      - flask run --host=0.0.0.0 --port=5000  # Start Flask app
artifacts:
  baseDirectory: /   # Specify base directory if needed
  files:
    - '**/*'  # Deploy all files in the directory
cache:
  paths:
    - '/root/.cache/pip/**/*'  # Cache pip dependencies for faster builds
